#!/usr/bin/php
<?php

/*
Enter the bash file folder
Adjust the require vendor path if needed
chmod u+x mybashphp
./mybashphp arg1 arg2
*/

require '../vendor/autoload.php';

echo "My Bash PHP by Gustavo Vinicius\n";

function myMemory() {
    $bytes = memory_get_usage();
    echo "\nRAM allocated bytes: {$bytes}\n";
}

function myDate() {
    $started = new \Datetime;
    echo "Started: {$started->format('Y-m-d H:i:s')}\n";
}

myDate();
myMemory();

print_r($argv);

echo "Illuminate Collection example:\n";

$oses = new Illuminate\Support\Collection();

$oses->push(...$argv);

print_r(json_encode($oses->values()->toArray()));

$ended = new \DateTime();

myDate();
myMemory();

?>