# # config/routes/attributes.yaml
# controllers:
#     resource:
#         path: ../../src/Core/
#         namespace: App\Core
#     type: rest

# kernel:
#     resource: App\Kernel
#     type: attribute